# Generated by Django 5.2 on 2025-04-13 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_nest_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMadePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('post_title', models.CharField(default='post title', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
