# Generated by Django 5.2 on 2025-04-13 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_nest_app', '0002_usermadepost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermadepost',
            name='post_title',
        ),
        migrations.AddField(
            model_name='usermadepost',
            name='title',
            field=models.CharField(default='post', max_length=255),
        ),
        migrations.AlterField(
            model_name='usermadepost',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
